twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    date:
        format: 'd F Y'
        timezone: 'Europe/Paris'
        

when@test:
    twig:
        strict_variables: true

knp_paginator:
    page_range: 5
    template:
        pagination: 'pagination/template.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'

            